# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-added-large-files
          exclude: "(uv.lock)"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
