sonar.projectKey=otterapi
sonar.projectName=otterapi
sonar.sources=otterapi
sonar.exclusions=otterapi/tests/**,otterapi/tests/fixtures/**
sonar.tests=otterapi/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
