name: 🚀 Feature Request
description: 'Suggest a new feature for otterapi'
labels: ["🚀 enhancement"]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing your ideas to otterapi! ✊

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest.

        You might like to add:
        * Some code suggestions
        * Your use case(s) for the feature
    validations:
      required: true
